#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.private"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.2ee2da0e3e8c95e90d78e234bcf2193869d115f8.name = "6.0~ynh2"
    test_upgrade_from.058508f95dd6b1f38bfd2808d7b5d6259656881f.name = "6.4~ynh1"
