#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.private"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.8f8961c239f890069c867e40005db98465add0c9.name = "5.0.20~ynh2"
    test_upgrade_from.c3675c322ec7b9e010f31db6bc59dd241a57dbf1.name = "5.0.41~ynh2"
    test_upgrade_from.2791ab29129baca48685277ce82ef763058b10cf.name = "5.0.41~ynh3"
