#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.private"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------
 # zabbix-cli is broken for these test, waiting if repaired
    test_upgrade_from.e7f03cd2148bfc349c3036cd135041246236e4ba.name  = "7.0~ynh7"
    test_upgrade_from.8a3a1b955017f7c2fee823aa4077a6c647c9ffc1.name = "7.0~ynh6"
    test_upgrade_from.b00499f4551009b07638813212fb20740150454e.name = "6.4~ynh1"