#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.private"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------
 # zabbix-cli is broken for these test, waiting if repaired
    test_upgrade_from.1fcdd73ec4682af7dc1af7622c2feb214ae75aa9.name = "7.0~ynh3"
    test_upgrade_from.b00499f4551009b07638813212fb20740150454e.name = "6.4~ynh1"