#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.private"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.ad5cc3f49b6c9c76e9f065ed5a0e927bbd83baf3.name = "7.0~ynh1"
    #test_upgrade_from.b00499f4551009b07638813212fb20740150454e.name = "6.4~ynh1"