UserParameter=yunohost.users.discover,sudo __INSTALL_DIR__/scripts/yunohost.sh yunohost.users.discover
UserParameter=yunohost.user.quota[*],sudo __INSTALL_DIR__/scripts/yunohost.sh yunohost.user.quota "$1"
UserParameter=yunohost.domains.discover,sudo __INSTALL_DIR__/scripts/yunohost.sh yunohost.domains.discover
UserParameter=yunohost.domain.cert[*],sudo __INSTALL_DIR__/scripts/yunohost.sh yunohost.domain.cert "$1"
UserParameter=yunohost.services.discover,sudo __INSTALL_DIR__/scripts/yunohost.sh yunohost.services.discover
UserParameter=yunohost.service.status[*],sudo __INSTALL_DIR__/scripts/yunohost.sh yunohost.service.status "$1"
UserParameter=yunohost.backups.number,sudo __INSTALL_DIR__/scripts/yunohost.sh yunohost.backups.number
UserParameter=yunohost.backups.ageoflastbackup,sudo __INSTALL_DIR__/scripts/yunohost.sh yunohost.backups.ageoflastbackup
UserParameter=yunohost.ports.tcp.discover,sudo __INSTALL_DIR__/scripts/yunohost.sh yunohost.ports.tcp.discovery
UserParameter=yunohost.ports.udp.discover,sudo __INSTALL_DIR__/scripts/yunohost.sh yunohost.ports.udp.discovery
UserParameter=yunohost.migrations.lastinstalled,sudo __INSTALL_DIR__/scripts/yunohost.sh yunohost.migrations.lastinstalled
UserParameter=yunohost.migrations.lastavailable,sudo __INSTALL_DIR__/scripts/yunohost.sh yunohost.migrations.lastavailable
