; Other common parameters
php_admin_value[max_execution_time] = 300
php_admin_value[max_input_time] = 300
; php_admin_value[memory_limit] = 256M
; php_admin_flag[short_open_tag] = On
php_admin_value[open_basedir] = /usr/share/zabbix/:/usr/share/fonts/:/tmp:/etc/zabbix/web
php_admin_value[date.timezone] = __TIMEZONE__