[api]
url = "https://__DOMAIN____PATH__"
username = "Admin"
password = "zabbix"
auth_token = ""
verify_ssl = false

[app]
use_auth_token_file = true
auth_token_file = "/usr/share/zabbix-cli/.zabbix-cli_auth_token"
auth_file = "/usr/share/zabbix-cli/.zabbix-cli_auth"
allow_insecure_auth_file = true
history = true
history_file = "/usr/share/zabbix-cli/history"
bulk_mode = "strict"
legacy_json_format = false

[app.commands.create_host]
create_interface = true
hostgroups = [
  "All-hosts",
]

[app.commands.create_group]
ro_groups = []
rw_groups = []

[app.commands.create_hostgroup]
ro_groups = []
rw_groups = []

[app.commands.create_templategroup]
ro_groups = []
rw_groups = []

[app.commands.create_user]
usergroups = []

[app.commands.create_notification_user]
usergroups = [
  "All-notification-users",
]

[app.commands.export]
directory = "/usr/share/zabbix-cli/exports"
format = "json"
timestamps = false


[app.output]
format = "table"
color = true
paging = false
theme = "default"

[logging]
enabled = true
log_level = "INFO"
log_file = "/usr/share/zabbix-cli/log/zabbix-cli.log"

[plugins]
