#!/bin/bash
source /usr/share/yunohost/helpers

user=$1
app="ynhzabbix"

db_name=$(ynh_app_setting_get $app db_name)
db_user=$(ynh_app_setting_get $app db_user)
db_pwd=$(ynh_app_setting_get $app mysqlpwd)

mysql -u$db_user -p$db_pwd $db_name -e "DELETE FROM users WHERE alias=\"$1\";"