#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_print_info --message="Declaring files to be backed up..."

#=================================================
# BACKUP THE SYSTEM CONFIGURATION
#=================================================

ynh_backup --src_path="/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup --src_path="/etc/php/$phpversion/fpm/pool.d/$app.conf"

#=================================================
# BACKUP VARIOUS FILES
#=================================================

# Backup frontend config
ynh_backup --src_path="/etc/zabbix/web"
ynh_backup --src_path="/etc/apt/apt.conf.d/100update_force_init_zabbix_frontend_config"

# Backup server config
ynh_backup --src_path="/etc/zabbix/zabbix_server.conf"

# Backup agent config
ynh_backup --src_path="/etc/zabbix/zabbix_agentd.conf"
ynh_backup --src_path="/etc/zabbix/zabbix_agentd.d"

# Backup sudo file
ynh_backup --src_path="/etc/sudoers.d/zabbix"

# Backup zabbix-cli
ynh_backup --src_path="/usr/share/zabbix-cli"

# Backup pinning preferences repo
yhn_backup --src_path="/etc/apt/preferences.d/zabbix_repo"

#=================================================
# BACKUP THE MYSQL DATABASE
#=================================================
ynh_print_info --message="Backing up the MySQL database..."

ynh_mysql_dump_db --database="$db_name" > db.sql

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
