#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set_default --key="zabbix_password" --value="$(ynh_string_random --length=32)"

#=================================================
# Create initial directory
#=================================================

mkdir -p "$install_dir/scripts"
mkdir -p /etc/zabbix/web

if [ ! -L "/usr/share/zabbix/ui/conf/zabbix.conf.php" ]
then
	ln -s /etc/zabbix/web/zabbix.conf.php /usr/share/zabbix/ui/conf/zabbix.conf.php
fi

#=================================================
# SETUP Code
#=================================================

ynh_script_progression "Creating venv for zabbix ynh tools"
python3 -m venv "$install_dir/zabbix_api"
"$install_dir/zabbix_api/bin/pip" install -r "$YNH_APP_BASEDIR/conf/requirement.txt"

ynh_script_progression 'Install scripts'

cp '../sources/yunohost.sh' "$install_dir/scripts/yunohost.sh"
ynh_config_add --template='../sources/init-zabbix-config.sh' --destination="$install_dir/scripts/init-zabbix-config.sh"

#=================================================
# IMPORT DEFAULT DATA
#=================================================
ynh_script_progression "Import default data in database..."

export mysqlconn="mysql --user=$db_user --password=$db_pwd --database=$db_name"

zcat /usr/share/zabbix/sql-scripts/mysql/server.sql.gz | $mysqlconn

convert_ZabbixDB

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_replace --match="# ${language}\.UTF-8 UTF-8" --replace="${language}\.UTF-8 UTF-8" --file="/etc/locale.gen"
locale-gen

ynh_app_setting_set_default --key="timezone" --value="$timezone"

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)

ynh_app_setting_set_default --key="php_process_management" --value="dynamic"
ynh_app_setting_set_default --key="php_start_servers" --value="2"
ynh_app_setting_set_default --key="php_min_spare_servers" --value="1"
ynh_app_setting_set_default --key="php_max_spare_servers" --value="3"
ynh_app_setting_set_default --key="php_slowlog" --value="/var/log/nginx/$app.slow.log"
ynh_app_setting_set_default --key="php_request_slowlog_timeout" --value="5s"
ynh_app_setting_set_default --key="php_chdir" --value="/usr/share/zabbix"
ynh_app_setting_set_default --key="php_catch_workers_output" --value="yes"
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

ynh_config_add --template=/etc_sudoers.d_zabbix --destination=/etc/sudoers.d/zabbix

#=================================================
# Zabbix configuration
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="zabbix.conf.php" --destination='/etc/zabbix/web/zabbix.conf.php'

ynh_config_add --template="etc_apt_preferences.d_zabbix" --destination="/etc/apt/preferences.d/zabbix_repo"

# TODO we would like to use template instead of fixing the config file
ynh_replace --match="DBName=zabbix" --replace="DBName=$db_name" --file="/etc/zabbix/zabbix_server.conf"
ynh_replace --match="DBUser=zabbix" --replace="DBUser=$db_user" --file="/etc/zabbix/zabbix_server.conf"
ynh_replace --match="# DBPassword=" --replace="# DBPassword=\nDBPassword=$db_pwd" --file="/etc/zabbix/zabbix_server.conf"

# TODO we would like to use template instead of fixing the config file
change_timeoutAgent

systemctl enable zabbix-agent --quiet
systemctl enable zabbix-server --quiet
yunohost service add snmpd --description="Management of SNMP Daemon"
yunohost service add zabbix-server --description="Management Zabbix server daemon : collect, agregate, compute and notify" --log="/var/log/$app/${app}_server.log"
yunohost service add zabbix-agent --description="Management Zabbix agent daemon : send informations about this host to the server" --log="/var/log/$app/${app}_agent.log"

update_initZabbixConf

set_permissions

# Start a systemd service
ynh_systemctl --service="$app-server" --action="restart" --log_path="/var/log/$app/${app}_server.log"
ynh_systemctl --service="$app-agent" --action="restart" --log_path="/var/log/$app/${app}_agent.log"

#=================================================
# Zabbix first configuration
#=================================================

$zabbix_tools configure_cli_user

$zabbix_tools configure_ldap_auth

$zabbix_tools disable_guest_user

$zabbix_tools disable_initial_admin_user

$zabbix_tools configure_mediatype

import_template

$zabbix_tools link_template

$zabbix_tools disable_superadmin_ynh

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app-server" --action="restart" --log_path="/var/log/$app/${app}_server.log"
ynh_systemctl --service="$app-agent" --action="restart" --log_path="/var/log/$app/${app}_agent.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
