#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

zabbix_username="svc_${app}_ldap"
zabbix_password=$(ynh_string_random --length=32)

ynh_app_setting_set --app="$app" --key=zabbix_username --value="$zabbix_username"
ynh_app_setting_set --app="$app" --key=zabbix_password --value="$zabbix_password"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

chmod -R o-rwx "/usr/share/zabbix"
chown -R "$app:www-data" "/usr/share/zabbix"

#=================================================
# IMPORT DEFAULT DATA
#=================================================
ynh_script_progression "Import default data in database..."

export mysqlconn="mysql --user=$db_user --password=$db_pwd --database=$db_name"
$mysqlconn -e "ALTER DATABASE $db_name CHARACTER SET utf8 COLLATE utf8_general_ci;"

zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | $mysqlconn

convert_ZabbixDB

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="etc_zabbix_web_zabbix.conf.php" --destination="/etc/zabbix/web/zabbix.conf.php"

ynh_config_add --template="etc_apt_preferences.d_zabbix" --destination="/etc/apt/preferences.d/zabbix_repo"

chmod 644 "/etc/apt/preferences.d/zabbix_repo"
chmod 400 "/etc/zabbix/web/zabbix.conf.php"
chown "$app:www-data" "/etc/zabbix/web/zabbix.conf.php"

ynh_replace --match="DBName=zabbix" --replace="DBName=$db_name" --file="/etc/zabbix/zabbix_server.conf"
ynh_replace --match="DBUser=zabbix" --replace="DBUser=$db_user" --file="/etc/zabbix/zabbix_server.conf"
ynh_replace --match="# DBPassword=" --replace="# DBPassword=\nDBPassword=$db_pwd" --file="/etc/zabbix/zabbix_server.conf"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_replace --match="# ${language}\.UTF-8 UTF-8" --replace="${language}\.UTF-8 UTF-8" --file="/etc/locale.gen"
locale-gen

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

change_timeoutAgent

systemctl enable zabbix-agent --quiet
systemctl enable zabbix-server --quiet
yunohost service add snmpd --description="Management of SNMP Daemon"
yunohost service add zabbix-server --description="Management Zabbix server daemon : collect, agregate, compute and notify" --log="/var/log/$app/${app}_server.log"
yunohost service add zabbix-agent --description="Management Zabbix agent daemon : send informations about this host to the server" --log="/var/log/$app/${app}_agent.log"

update_initZabbixConf

#=================================================
# SETUP APPLICATION
#=================================================
ynh_script_progression "Setting up application..."

ynh_print_info "Installing zabbix-cli"
mkdir -p /usr/share/zabbix-cli
python3 -m venv /usr/share/zabbix-cli
/usr/share/zabbix-cli/bin/pip install zabbix-cli-uio

# ldap zabbix user creation
ynh_print_info "Creating ldap zabbix user"
yunohost user create "$zabbix_username" --fullname "${zabbix_username//_}" --domain "$domain" --password "$zabbix_password" -q 0
ynh_config_add --template="zabbix-cli_default.toml" --destination="/usr/share/zabbix-cli/zabbix-cli.toml"
/usr/share/zabbix-cli/bin/zabbix-cli --config "/usr/share/zabbix-cli/zabbix-cli.toml" create_user "$zabbix_username" --firstname "$zabbix_username" --lastname "$zabbix_username" --passwd "$zabbix_password" --role superadmin --groups 7
ynh_config_add --template="zabbix-cli.toml" --destination="/usr/share/zabbix-cli/zabbix-cli.toml"
ynh_safe_rm "/usr/share/zabbix-cli/.zabbix-cli_auth_token"

# sso integration activation
ynh_print_info "Enabling LDAP authentication"
$mysqlconn -e "UPDATE \`config\` SET \`http_auth_enabled\` = '1', \`http_login_form\` = '1' WHERE \`config\`.\`configid\` = 1;"
#Ldap integration activation
$mysqlconn -e "INSERT INTO \`userdirectory\` (\`userdirectoryid\`,\`name\`, \`description\`, \`idp_type\`, \`provision_status\`) VALUES (1,'localhost', '', '1', '0');"
$mysqlconn -e "INSERT INTO \`userdirectory_ldap\` (\`userdirectoryid\`,\`host\`, \`port\`, \`base_dn\`, \`search_attribute\`, \`bind_dn\`, \`bind_password\`, \`start_tls\`, \`search_filter\`, \`group_basedn\`, \`group_name\`, \`group_member\`, \`user_ref_attr\`, \`group_filter\`, \`group_membership\`, \`user_username\`, \`user_lastname\`) VALUES (1,'127.0.0.1', '389', 'ou=users,dc=yunohost,dc=org', 'uid', '', '', '0', '', '', '', '', '', '', '', '', '');"
$mysqlconn -e "UPDATE \`config\` SET \`authentication_type\` = '1', \`ldap_auth_enabled\` = '1', \`ldap_userdirectoryid\` = '1' WHERE \`config\`.\`configid\` = 1;"

# admin user creation
ynh_print_info "Creating admin user"
lastname=$(ynh_user_get_info "$admin" lastname)
firstname=$(ynh_user_get_info "$admin" firstname)
/usr/share/zabbix-cli/bin/zabbix-cli --config /usr/share/zabbix-cli/zabbix-cli.toml create_user "$admin" --firstname "$firstname" --lastname "$lastname" --role superadmin --groups 7

# users creation
ynh_print_info "Creating all users"
for user in $(ynh_user_list);
do
	if [ "$user" != "$admin" ] && [ "$user" != "$zabbix_username" ] && [ "$user" != "admin" ] && [ "$user" != "guest" ]
	then
		lastname=$(ynh_user_get_info --username="$user" --key=lastname)
		firstname=$(ynh_user_get_info --username="$user" --key=firstname)
		/usr/share/zabbix-cli/bin/zabbix-cli --config /usr/share/zabbix-cli/zabbix-cli.toml create_user $user --firstname $firstname --lastname $lastname --role user --groups 8
	fi
done

disable_guest_user

disable_admin_user

set_mediatype_default_yunohost

import_template

link_template

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app-server" --action="restart" --log_path="/var/log/$app/${app}_server.log"
ynh_systemctl --service="$app-agent" --action="restart" --log_path="/var/log/$app/${app}_agent.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
