#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the dedicated systemd config
ynh_systemctl --service="$app-server" --action="stop" --log_path="/var/log/$app/${app}_server.log"
ynh_systemctl --service="$app-agent" --action="stop" --log_path="/var/log/$app/${app}_agent.log"
systemctl disable zabbix-server --quiet
systemctl disable zabbix-agent --quiet
ynh_hide_warnings killall zabbix_server
ynh_hide_warnings killall zabbix_agentd

yunohost service remove snmpd
yunohost service remove zabbix-server
yunohost service remove zabbix-agent

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove the dedicated PHP-FPM config
ynh_config_remove_phpfpm

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression "Removing $app's configuration..."

# Remove config file detection
delete_initZabbixConf

ynh_safe_rm "/usr/share/$app"

#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

# Remove a directory securely
ynh_safe_rm "/etc/$app"

# Remove the log files

ynh_safe_rm "/run/$app"

ynh_safe_rm "/etc/sudoers.d/$app"

# FIXME: useless?
# REMOVE NONFREE PART PATCH IF NEEDED (snmp-mibs-downloader (non-free) installed in version 1)
nonfreepackagelist=$(dpkg-query -W -f='${Section}\t${Package}\n' | grep ^non-free)
if [ "$(echo $nonfreepackagelist | wc -l)" -eq 1 ] && [ "$(echo $nonfreepackagelist | grep -c "snmp-mibs-downloader")" -eq 1 ]; then
    ynh_print_info "Removing snmp-mibs-downloader (non-free package)"
    cp /var/lib/dpkg/status{,.$(date "+%m%d%y")}
    ynh_replace --match=" snmp-mibs-downloader," --replace="" --file=/var/lib/dpkg/status
    DEBIAN_FRONTEND=noninteractive apt purge snmp-mibs-downloader -y
    if [ -f /etc/apt/sources.list.d/non-free.list ]; then
        ynh_safe_rm "/etc/apt/sources.list.d/non-free.list"
    fi
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
